### ISSUE TITLE
java.lang.SecurityException: JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by asabeeh18** [encryptedsystems/Clusion#10]
Following the instructions from your README.md i still can't get it to run.

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.crypto.sse.RR2Lev.constructEMMParGMM(RR2Lev.java:246)
        at org.crypto.sse.TestLocalRR2Lev.main(TestLocalRR2Lev.java:57)
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at javax.crypto.Cipher.getInstance(Cipher.java:657)
        at javax.crypto.Cipher.getInstance(Cipher.java:596)
        at org.crypto.sse.CryptoPrimitives.encryptAES_CTR_String(CryptoPrimitives.java:229)
        at org.crypto.sse.RR2Lev.setup(RR2Lev.java:288)
        at org.crypto.sse.RR2Lev$2.call(RR2Lev.java:236)
        at org.crypto.sse.RR2Lev$2.call(RR2Lev.java:233)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.jar.JarException: file:/F:/MTech/Kh/Thesis/1Clusion/target/Clusion-1.0-SNAPSHOT-jar-with-dependencies.jar has unsigned entries - org/crypto/sse/CryptoPrimitives.class
        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:500)
        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:361)
        at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:159)
        at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:185)
        at javax.crypto.Cipher.getInstance(Cipher.java:653)
        ... 9 more

```

**Comment by gameProphet** [comment]
Hi, somehow I encountered the same issue while running quickTest. I'm not sure whether we face the same problem or not. My problem got solved by following three steps which you could try. Good luck.

1.download the jar file for bouncycastle from https://www.bouncycastle.org/latest_releases.html
2.place the jar file (i.e., bcprov-jdk15on-159.jar) to the /home/XXX/Clusion/target folder.
3.add bcprov-jdk15on-159.jar to CLASSPATH,
For example, my CLASSPATH is CLASSPATH=/home/XXX/Clusion/target/classes:/home/XXX/Clusion/target/test-classes:/home/XXX/Clusion/target/bcprov-jdk15on-159.jar:/home/XXX/Clusion/target/Clusion-1.0-SNAPSHOT-jar-with-dependencies.jar

**Comment by Guss123** [comment]
I ran into a similar error and on MACOS, what worked for me was that I placed bcprov-ext-jdk15on-160.jar in jre/lib/ext located in the Java installation folder. 
I am not sure if this is the best way to tackle this issue.

**Comment by alankamali** [comment]
Hi, I've ran into the same problem and have tried both approaches, still having the same error.
Not sure what I'm missing here. Would really appreciate any help as I've been stuck for a while now ..

<img width="1291" alt="Screenshot 2023-09-20 at 3 02 18 pm" src="https://github.com/encryptedsystems/Clusion/assets/66233493/22da9e56-6d07-4934-8445-06921fbb0091">
